FROM nginx:alpine
ENV STARTUP_TIME=15

COPY index.html /usr/share/nginx/html/index.html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY init.sh /app/init.sh

RUN chmod u+x /app/init.sh

EXPOSE 8080

CMD ["/app/init.sh"]
